"""Update EmailOutbox (replace it's responsibility and rename)

Revision ID: 70757c8640ee
Revises: 8a4b86fce389
Create Date: 2026-01-19 14:15:04.807226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70757c8640ee'
down_revision: Union[str, Sequence[str], None] = '8a4b86fce389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_type', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_emails_id'), 'sent_emails', ['id'], unique=False)
    op.create_index(op.f('ix_sent_emails_user_id'), 'sent_emails', ['user_id'], unique=False)
    op.drop_index(op.f('ix_email_outbox_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_user_id'), table_name='email_outbox')
    op.drop_table('email_outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'failed', name='email_status_enum'), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('email_outbox_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_outbox_pkey'))
    )
    op.create_index(op.f('ix_email_outbox_user_id'), 'email_outbox', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_outbox_id'), 'email_outbox', ['id'], unique=False)
    op.drop_index(op.f('ix_sent_emails_user_id'), table_name='sent_emails')
    op.drop_index(op.f('ix_sent_emails_id'), table_name='sent_emails')
    op.drop_table('sent_emails')
    # ### end Alembic commands ###
