"""Remove useless fields ip_address and user_agent from table RefreshToken

Revision ID: 8a4b86fce389
Revises: 1ad4c7e3f8a3
Create Date: 2026-01-18 16:37:28.483361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a4b86fce389'
down_revision: Union[str, Sequence[str], None] = '1ad4c7e3f8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
