#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE ${AUTH_DB_USER} WITH LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  CREATE ROLE ${NOTES_DB_USER} WITH LOGIN PASSWORD '${NOTES_DB_PASSWORD}';
EOSQL
