#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE auth_user WITH LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  CREATE ROLE notes_user WITH LOGIN PASSWORD '${NOTES_DB_PASSWORD}';
EOSQL
