#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE auth_local OWNER ${AUTH_DB_USER};
  CREATE DATABASE auth_dev OWNER ${AUTH_DB_USER};
  CREATE DATABASE auth_test OWNER ${AUTH_DB_USER};

  CREATE DATABASE notes_local OWNER ${NOTES_DB_USER};
  CREATE DATABASE notes_dev OWNER ${NOTES_DB_USER};
  CREATE DATABASE notes_test OWNER ${NOTES_DB_USER};
EOSQL
